services:
  backend:
    container_name: mht-backend
    restart: always
    build:
      context: ./ 
      dockerfile: backend/Dockerfile
    ports:
      - "5006:3001"
    volumes:
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
  frontend:
    container_name: mht-frontend
    restart: always
    volumes:
      - ./.env:/app/.env.local
    build:
      context: ./ 
      dockerfile: frontend/Dockerfile
    ports:
      - "5005:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}

  